services:
  be:
    image: 864573346741.dkr.ecr.ap-northeast-2.amazonaws.com/tag2-now/be
    ports:
      - "8000:8000"
    environment:
      FAST_API_PROFILE: dev
      DB_TYPE: dynamodb
      DYNAMODB_REGION: ap-northeast-2
      DYNAMODB_TABLE_NAME: tag2now-community
      DYNAMODB_ENDPOINT_URL: http://dynamodb-local:8000
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - redis
      - dynamodb-local
  fe:
    image: 864573346741.dkr.ecr.ap-northeast-2.amazonaws.com/tag2-now/fe
    ports:
      - "80:80"
    environment:
      BACKEND_URL: http://be:8000

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"