"""Tekken Tag Tournament 2 static data (character tables, etc.)."""

# Character ID → name mapping (hex IDs from game_info bytes)
TTT2_CHARACTERS = {
	0x00: "Paul",
	0x01: "Law",
	0x02: "Lei",
	0x03: "King",
	0x04: "Yoshimitsu",
	0x05: "Nina",
	0x06: "Hwoarang",
	0x07: "Xiayu",
	0x08: "Christie",
	0x09: "Jin",
	0x0A: "Julia",
	0x0B: "Kuma",
	0x0C: "Bryan",
	0x0D: "Heihachi",
	0x0E: "Kazuya",
	0x0F: "Lee",
	0x10: "Steve",
	0x11: "Marduk",
	0x12: "Mokujin",
	0x13: "Jack",
	0x14: "Roger Jr.",
	0x15: "Anna",
	0x16: "Wang",
	0x17: "Ganryu",
	0x18: "Asuka",
	0x19: "Bruce",
	0x1A: "Baek",
	0x1B: "Devil Jin",
	0x1C: "Raven",
	0x1D: "Feng",
	0x1E: "Armor King",
	0x1F: "Lili",
	0x20: "Dragunov",
	0x21: "Eddy",
	0x22: "Bob",
	0x23: "Zafina",
	0x24: "Miguel",
	0x25: "Leo",
	0x26: "Lars",
	0x27: "Alisa",
	0x28: "Jinpachi",
	0x29: "True Ogre",
	0x2A: "Jun",
	0x2B: "Combot",
	0x2C: "Unknown",
	0x2D: "Kunimitsu",
	0x2E: "Michelle",
	0x2F: "Forest Law",
	0x30: "Miharu",
	0x31: "",
	0x32: "?",
	0x33: "Michelle",
	0x34: "P-Jack",
	0x35: "Sebastian",
	0x36: "Ancient Ogre",
	0x37: "Violet",
	0x38: "Dr.",
	0x39: "Slim Bob",
	0x3A: "Tiger"
}

TEKKEN_RANKS = {
	0: {"name": "Beginner", "tier": "숫자단"},
	1: {"name": "9th kyu", "tier": "숫자단"},
	2: {"name": "8th kyu", "tier": "숫자단"},
	3: {"name": "7th kyu", "tier": "숫자단"},
	4: {"name": "6th kyu", "tier": "숫자단"},
	5: {"name": "5th kyu", "tier": "숫자단"},
	6: {"name": "4th kyu", "tier": "숫자단"},
	7: {"name": "3rd kyu", "tier": "숫자단"},
	8: {"name": "2nd kyu", "tier": "숫자단"},
	9: {"name": "1st kyu", "tier": "숫자단"},
	10: {"name": "1st dan", "tier": "숫자단"},
	11: {"name": "2nd dan", "tier": "숫자단"},
	12: {"name": "3rd dan", "tier": "숫자단"},
	13: {"name": "Disciple", "tier": "액자단"},
	14: {"name": "Mentor", "tier": "액자단"},
	15: {"name": "Master", "tier": "액자단"},
	16: {"name": "Grand Master", "tier": "액자단"},
	17: {"name": "Brawler", "tier": "녹단"},
	18: {"name": "Marauder", "tier": "녹단"},
	19: {"name": "Fighter", "tier": "녹단"},
	20: {"name": "Berserker", "tier": "녹단"},
	21: {"name": "Warrior", "tier": "노랑단"},
	22: {"name": "Avenger", "tier": "노랑단"},
	23: {"name": "Duelist", "tier": "노랑단"},
	24: {"name": "Pugilist", "tier": "노랑단"},
	25: {"name": "Vanquisher", "tier": "주황단"},
	26: {"name": "Destroyer", "tier": "주황단"},
	27: {"name": "Conqueror", "tier": "주황단"},
	28: {"name": "Savior", "tier": "주황단"},
	29: {"name": "Genbu", "tier": "빨강단"},
	30: {"name": "Byakko", "tier": "빨강단"},
	31: {"name": "Seiryu", "tier": "빨강단"},
	32: {"name": "Suzaku", "tier": "빨강단"},
	33: {"name": "Fujin", "tier": "파랑단"},
	34: {"name": "Raijin", "tier": "파랑단"},
	35: {"name": "Yaksa", "tier": "파랑단"},
	36: {"name": "Majin", "tier": "파랑단"},
	37: {"name": "Toshin", "tier": "파랑단"},
	38: {"name": "Emperor", "tier": "보라단"},
	39: {"name": "Tekken Lord", "tier": "보라단"},
	40: {"name": "Tekken Emperor", "tier": "보라단"},
	41: {"name": "Tekken God", "tier": "God"},
	42: {"name": "True Tekken God", "tier": "God"}
}