apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rpcn-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rpcn-credentials
    creationPolicy: Owner
  data:
    - secretKey: RPCN_USER
      remoteRef:
        key: rpcn-client/credentials
        property: RPCN_USER
    - secretKey: RPCN_PASSWORD
      remoteRef:
        key: rpcn-client/credentials
        property: RPCN_PASSWORD
